#!/usr/bin/env bash

test -d release || exit 1
IMAGE_ID=$(docker build --quiet --file release/Dockerfile .)
NAME=`basename "$(pwd)"`
TAG="$NAME:latest"
docker tag $IMAGE_ID $TAG
for arg in "$@"
do
    if [ "$arg" == "--transfer" ]
    then
        docker save $TAG | bzip2 | pv | ssh vagrant@localhost -p 2201 'bunzip2 | docker load'
    fi

    if [ "$arg" == "--deploy" ]
    then
        ssh vagrant@localhost -p 2201 <<EOF
OLD=\$(docker ps --quiet --filter 'ancestor=$TAG')
NEW=\$(docker run --detach --label hostname=$NAME --publish 80 $TAG)
test ! -z "\$OLD" && docker stop \$OLD
EOF
    fi
done

